export const DEMO_PRODUCTS = [
  {
    _id: '1',
    name: 'Luna Rosewood',
    slug: 'luna-rosewood',
    description: 'A sophisticated arrangement of deep red preserved roses in an elegant black vase.',
    price: 1890,
    category: { name: 'Interior Vase Bouquets', slug: 'interior-vase-bouquets' },
    images: ['https://inbloom.ae/wp-content/uploads/61611C01-32D3-4F9A-8574-A42D3862F129.jpg'],
    stockStatus: 'in-stock',
    countInStock: 10,
  },
  {
    _id: '2',
    name: 'Lana – Serotonin',
    slug: 'lana-serotonin',
    description: 'Vibrant yellow and orange preserved roses designed to uplift any space.',
    price: 2460,
    category: { name: 'Signature Boxes Collection', slug: 'signature-boxes' },
    images: ['https://inbloom.ae/wp-content/uploads/706719212_17960656125104145_777686201114964296_n.jpg'],
    stockStatus: 'in-stock',
    countInStock: 5,
  },
  {
    _id: '3',
    name: 'Eternal Ruby Box',
    slug: 'eternal-ruby-box',
    description: 'Our classic black velvet box filled with timeless red preserved roses.',
    price: 1200,
    category: { name: 'Flower Boxes', slug: 'flower-boxes' },
    images: ['https://inbloom.ae/wp-content/uploads/IMG_2875-scaled.webp'],
    stockStatus: 'in-stock',
    countInStock: 20,
  },
  {
    _id: '4',
    name: 'Bridal White Collection',
    slug: 'bridal-white-collection',
    description: 'Pure white preserved roses arranged flawlessly for a pristine look.',
    price: 2100,
    category: { name: 'Wedding Flowers', slug: 'wedding-flowers' },
    images: ['https://inbloom.ae/wp-content/uploads/2026/01/DO01050011.jpg'],
    stockStatus: 'in-stock',
    countInStock: 8,
  },
  {
    _id: '5',
    name: 'Spring Essence',
    slug: 'spring-essence',
    description: 'A soft blend of pink and peach preserved roses capturing the spirit of spring.',
    price: 1650,
    category: { name: 'Seasonal Collections', slug: 'seasonal-collections' },
    images: ['https://inbloom.ae/wp-content/uploads/2025/05/L1080140-Photoroom-3.jpg'],
    stockStatus: 'in-stock',
    countInStock: 15,
  },
  {
    _id: '6',
    name: 'Majestic Emerald',
    slug: 'majestic-emerald',
    description: 'Striking preserved green orchids making a bold interior statement.',
    price: 3200,
    category: { name: 'Interior Statement Pieces', slug: 'interior-statement-pieces' },
    images: ['https://inbloom.ae/wp-content/uploads/2025/05/green-orchids-Photoroom-7-e1746599286884.jpg'],
    stockStatus: 'in-stock',
    countInStock: 3,
  },
  {
    _id: '7',
    name: 'Blush Petite Box',
    slug: 'blush-petite-box',
    description: 'A smaller luxury box featuring delicate blush pink preserved roses.',
    price: 850,
    category: { name: 'Flower Boxes', slug: 'flower-boxes' },
    images: ['https://images.unsplash.com/photo-1582794543139-8ac9cb0f7b11?auto=format&fit=crop&q=80&w=800'],
    stockStatus: 'in-stock',
    countInStock: 12,
  },
  {
    _id: '8',
    name: 'Royal Velvet Vase',
    slug: 'royal-velvet-vase',
    description: 'Deep burgundy preserved roses in an intricate ceramic vase.',
    price: 2800,
    category: { name: 'Interior Vase Bouquets', slug: 'interior-vase-bouquets' },
    images: ['https://images.unsplash.com/photo-1560717845-968823efbee1?auto=format&fit=crop&q=80&w=800'],
    stockStatus: 'in-stock',
    countInStock: 6,
  }
];
